In [2]:
import numpy as np
import matplotlib.pyplot as plt

A = np.random.rand(3,4)
A = A * 5 - 2.5 

print(A)

[[ 1.64291739 -2.46606515  0.29142398 -1.72213863]
 [ 2.43388715 -1.08180881  2.17373969  0.19674727]
 [ 0.56836944 -0.01738692 -1.2827353   0.99608332]]


In [43]:
print("Matrice originale :\n", A)
print("\nArrondi supérieur (ceil) :\n", np.ceil(A))
print("\nArrondi inférieur (floor) :\n", np.floor(A))
print("\nArrondi au plus proche (around) :\n", np.around(A))
print("\nValeur tronquée (trunc) :\n", np.trunc(A))

Matrice originale :
 [[ 1.31619698  0.12490056 -2.20652041  0.19928046]
 [-2.41391274 -1.51518261  0.85517291 -2.2441378 ]
 [-1.07569744 -1.84805711  1.2587608   0.48182749]]

Arrondi supérieur (ceil) :
 [[ 2.  1. -2.  1.]
 [-2. -1.  1. -2.]
 [-1. -1.  2.  1.]]

Arrondi inférieur (floor) :
 [[ 1.  0. -3.  0.]
 [-3. -2.  0. -3.]
 [-2. -2.  1.  0.]]

Arrondi au plus proche (around) :
 [[ 1.  0. -2.  0.]
 [-2. -2.  1. -2.]
 [-1. -2.  1.  0.]]

Valeur tronquée (trunc) :
 [[ 1.  0. -2.  0.]
 [-2. -1.  0. -2.]
 [-1. -1.  1.  0.]]


In [44]:
B = np.delete(A,-1,axis=1) # Méthode pour supp une ligne  
print("\nMatrice B après suppression de la dernière colonne de A :\n", A)


Matrice B après suppression de la dernière colonne de A :
 [[ 1.31619698  0.12490056 -2.20652041  0.19928046]
 [-2.41391274 -1.51518261  0.85517291 -2.2441378 ]
 [-1.07569744 -1.84805711  1.2587608   0.48182749]]


In [45]:
C = np.reshape(A,(2,6))
print("\nMatrice C (reshape de A):\n",C)


Matrice C (reshape de A):
 [[ 1.31619698  0.12490056 -2.20652041  0.19928046 -2.41391274 -1.51518261]
 [ 0.85517291 -2.2441378  -1.07569744 -1.84805711  1.2587608   0.48182749]]


Oui, c’est tout à fait possible.
B = np.delete(A, -1, axis=1) crée une nouvelle matrice B identique à A mais sans la dernière colonne.

Tu peux ensuite ajouter une dimension supplémentaire à B comme ceci

# Exercice 2 

In [46]:
V = np.array([1,2,3])
U = np.array([4,5,6])

E = np.zeros((5,3),dtype=int)

E[0,:] = U
E[-1,:] = V

print("\nMatrice E :\n",E)


Matrice E :
 [[4 5 6]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 2 3]]


# Exercice 3 

In [47]:
A = np.arange(16).reshape(4,4)
print("\nMatrice A construite avec arrange() : \n",A)
A_diag = np.diag(np.diag(A))
print("\nMatrice A diagonale : \n",A_diag)


Matrice A construite avec arrange() : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Matrice A diagonale : 
 [[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


Maintenant si l'on veut la matrice indiquer dans l'exo 3 : 

In [48]:
n = 5

main_diago = np.ones(n) * 2
diago_off = np.ones(n-1) * -1
A = np.diag(main_diago) + np.diag(diago_off,k=1) + np.diag(diago_off,k=-1)

print("\n Matrice A contruite avec diag off et main diago :\n",A)


 Matrice A contruite avec diag off et main diago :
 [[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


# Exercice 4 : 

In [49]:
n = 4 
A = np.arange(16).reshape((n,n))
D = np.diag([0.5,1,2,3])
print("\nMatrice A :\n",A)
print("\nMatrice D :\n",D)

prod_AD = np.dot(A,D)
print("\nProduit Matrice A et D  avec dot() :\n",prod_AD)
print("\nProduit avec l'opérateur *\n",A*D)


Matrice A :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Matrice D :
 [[0.5 0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  2.  0. ]
 [0.  0.  0.  3. ]]

Produit Matrice A et D  avec dot() :
 [[ 0.  1.  4.  9.]
 [ 2.  5. 12. 21.]
 [ 4.  9. 20. 33.]
 [ 6. 13. 28. 45.]]

Produit avec l'opérateur *
 [[ 0.  0.  0.  0.]
 [ 0.  5.  0.  0.]
 [ 0.  0. 20.  0.]
 [ 0.  0.  0. 45.]]


On remarque que l'opérateur * ne fait pas l'opération matritiel mais muttiplie éléments par éléments

# Exercice 5 

In [50]:
A = np.arange(25).reshape((5,5))
print("\nMatrice A : \n",A)

A_inf = np.tril(A,k=-1)

print("\n Matrice A (partie inf) : \n",A_inf)


Matrice A : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 Matrice A (partie inf) : 
 [[ 0  0  0  0  0]
 [ 5  0  0  0  0]
 [10 11  0  0  0]
 [15 16 17  0  0]
 [20 21 22 23  0]]


# Exercice 6 : 

In [51]:
A_exp = np.exp(A)
print("\nf(x) = exp(x): \n",A_exp)
A_tan = np.tan(2*np.pi*A)  
print("\nf(x) = tan(2*pi*x): \n",A_tan)
A_poly = 4*A**3-A+1  
print("\nf(x) = 4x³-x+1: \n",A_poly)
A_fact = (A-5)*(A+1)
print("\nf(x) = (x-5)(x+1): \n",A_fact)
A_div = 1/(1+A**2)  
print("\nf(x) = 1/(1+x²): \n",A_div)  


f(x) = exp(x): 
 [[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
  1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07 6.56599691e+07
  1.78482301e+08]
 [4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09
  2.64891221e+10]]

f(x) = tan(2*pi*x): 
 [[ 0.00000000e+00 -2.44929360e-16 -4.89858720e-16 -7.34788079e-16
  -9.79717439e-16]
 [-1.22464680e-15 -1.46957616e-15 -1.71450552e-15 -1.95943488e-15
  -2.20436424e-15]
 [-2.44929360e-15 -9.79965032e-15 -2.93915232e-15  3.92134568e-15
  -3.42901104e-15]
 [-1.07793678e-14 -3.91886976e-15  2.94162824e-15 -4.40872848e-15
  -1.17590852e-14]
 [-4.89858720e-15  1.96191080e-15 -1.95993006e-14 -1.27388026e-14
  -5.87830464e-15]]

f(x) = 4x³-x+1: 
 [[    1     4    31   106   253]
 [  496   859  1366  2041  2908]
 [ 3991  5314  6901  8776 10963]
 [13486 16369 

# Exercice 7 

Assemblage des bocks : 

In [3]:
A11 = np.array([[3,5,12],
                [3,-1,1],
                [2,-1,1]])
A21 = np.array([[0,0,3],
               [0,3,0]])
A12 = np.array([[0,0],
               [0,3],
               [3,0]])
A22 = np.array([[-1,0],
               [0,-1]])

A = np.block([[A11,A12],
             [A21,A22]])

print("\n Matrice A assemblé par block:\n",A)


 Matrice A assemblé par block:
 [[ 3  5 12  0  0]
 [ 3 -1  1  0  3]
 [ 2 -1  1  3  0]
 [ 0  0  3 -1  0]
 [ 0  3  0  0 -1]]


Extraction des blocks : 

In [4]:
A11_extract = A[:3,:3]
A12_extract = A[:3,3:]
A21_extract = A[3:,:3]
A22_extract = A[3:,3:]

print("A11 extrait :\n",A11_extract)
print("A12 extrait :\n",A12_extract)
print("A21 extrait :\n",A21_extract)
print("A22 extrait :\n",A22_extract)

A11 extrait :
 [[ 3  5 12]
 [ 3 -1  1]
 [ 2 -1  1]]
A12 extrait :
 [[0 0]
 [0 3]
 [3 0]]
A21 extrait :
 [[0 0 3]
 [0 3 0]]
A22 extrait :
 [[-1  0]
 [ 0 -1]]


Calcule des opérations éléments par éléments : 

In [5]:
print("Matrice A : \n",A)

op1 = 2 * A
op2 = 2 + A
op3 = A - 1
op4 = A/2.0

print("2 x A :\n",op1)
print("2 + A :\n",op2)
print("A - 1 :\n",op3)
print("A / 2 :\n",op4)

Matrice A : 
 [[ 3  5 12  0  0]
 [ 3 -1  1  0  3]
 [ 2 -1  1  3  0]
 [ 0  0  3 -1  0]
 [ 0  3  0  0 -1]]
2 x A :
 [[ 6 10 24  0  0]
 [ 6 -2  2  0  6]
 [ 4 -2  2  6  0]
 [ 0  0  6 -2  0]
 [ 0  6  0  0 -2]]
2 + A :
 [[ 5  7 14  2  2]
 [ 5  1  3  2  5]
 [ 4  1  3  5  2]
 [ 2  2  5  1  2]
 [ 2  5  2  2  1]]
A - 1 :
 [[ 2  4 11 -1 -1]
 [ 2 -2  0 -1  2]
 [ 1 -2  0  2 -1]
 [-1 -1  2 -2 -1]
 [-1  2 -1 -1 -2]]
A / 2 :
 [[ 1.5  2.5  6.   0.   0. ]
 [ 1.5 -0.5  0.5  0.   1.5]
 [ 1.  -0.5  0.5  1.5  0. ]
 [ 0.   0.   1.5 -0.5  0. ]
 [ 0.   1.5  0.   0.  -0.5]]


In [7]:
B = np.arange(25).reshape((5,5))
print("matrice B :\n",B)

B11_extract = B[:3,:3]
B12_extract = B[:3,3:]
B21_extract = B[3:,:3]
B22_extract = B[3:,3:]

print("Blocs extraits de B :")
print("B11 extrait :\n", B11_extract)
print("B12 extrait :\n", B12_extract)
print("B21 extrait :\n", B21_extract)
print("B22 extrait :\n", B22_extract)

# Produit par blocs
# Block matrix multiplication
C11 = np.dot(A11_extract, B11_extract) + np.dot(A12_extract, B21_extract)
C12 = np.dot(A11_extract, B12_extract) + np.dot(A12_extract, B22_extract)
C21 = np.dot(A21_extract, B11_extract) + np.dot(A22_extract, B21_extract)
C22 = np.dot(A21_extract, B12_extract) + np.dot(A22_extract, B22_extract)

res = np.block([[C11, C12],
                [C21, C22]])

print("\nA x B par blocs :\n",res)



matrice B :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Blocs extraits de B :
B11 extrait :
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
B12 extrait :
 [[ 3  4]
 [ 8  9]
 [13 14]]
B21 extrait :
 [[15 16 17]
 [20 21 22]]
B22 extrait :
 [[18 19]
 [23 24]]

A x B par blocs :
 [[145 165 185 205 225]
 [ 65  71  77  83  89]
 [ 50  55  60  65  70]
 [ 15  17  19  21  23]
 [ -5  -3  -1   1   3]]


# Exercice 8 