In [11]:
import numpy as np
import matplotlib.pyplot as plt

A = np.random.rand(3,4)
A = A * 5 - 2.5 

print(A)

[[-1.99429733 -0.82655813 -1.93680938  2.36585916]
 [ 1.66638421  1.87854134  1.1641232  -1.23484482]
 [ 1.63721482 -1.33167844  2.04027779  0.8654948 ]]


In [12]:
print("Matrice originale :\n", A)
print("\nArrondi supérieur (ceil) :\n", np.ceil(A))
print("\nArrondi inférieur (floor) :\n", np.floor(A))
print("\nArrondi au plus proche (around) :\n", np.around(A))
print("\nValeur tronquée (trunc) :\n", np.trunc(A))

Matrice originale :
 [[-1.99429733 -0.82655813 -1.93680938  2.36585916]
 [ 1.66638421  1.87854134  1.1641232  -1.23484482]
 [ 1.63721482 -1.33167844  2.04027779  0.8654948 ]]

Arrondi supérieur (ceil) :
 [[-1. -0. -1.  3.]
 [ 2.  2.  2. -1.]
 [ 2. -1.  3.  1.]]

Arrondi inférieur (floor) :
 [[-2. -1. -2.  2.]
 [ 1.  1.  1. -2.]
 [ 1. -2.  2.  0.]]

Arrondi au plus proche (around) :
 [[-2. -1. -2.  2.]
 [ 2.  2.  1. -1.]
 [ 2. -1.  2.  1.]]

Valeur tronquée (trunc) :
 [[-1. -0. -1.  2.]
 [ 1.  1.  1. -1.]
 [ 1. -1.  2.  0.]]


In [13]:
B = np.delete(A,-1,axis=1) # Méthode pour supp une ligne  
print("\nMatrice B après suppression de la dernière colonne de A :\n", A)


Matrice B après suppression de la dernière colonne de A :
 [[-1.99429733 -0.82655813 -1.93680938  2.36585916]
 [ 1.66638421  1.87854134  1.1641232  -1.23484482]
 [ 1.63721482 -1.33167844  2.04027779  0.8654948 ]]


In [14]:
C = np.reshape(A,(2,6))
print("\nMatrice C (reshape de A):\n",C)


Matrice C (reshape de A):
 [[-1.99429733 -0.82655813 -1.93680938  2.36585916  1.66638421  1.87854134]
 [ 1.1641232  -1.23484482  1.63721482 -1.33167844  2.04027779  0.8654948 ]]


Oui, c’est tout à fait possible.
B = np.delete(A, -1, axis=1) crée une nouvelle matrice B identique à A mais sans la dernière colonne.

Tu peux ensuite ajouter une dimension supplémentaire à B comme ceci

# Exercice 2 

In [15]:
V = np.array([1,2,3])
U = np.array([4,5,6])

E = np.zeros((5,3),dtype=int)

E[0,:] = U
E[-1,:] = V

print("\nMatrice E :\n",E)


Matrice E :
 [[4 5 6]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 2 3]]


# Exercice 3 