# Exercice 2

1. Utiliser la fonction  loadtxt du package  numpy en Python (ici désigné par  np ).
Cette fonction permet de lire les fichiers et de les concertir en vecteurs/matrices :

In [21]:
import numpy as np 

x = np.loadtxt('ex2dat/ex2x.dat')
y = np.loadtxt('ex2dat/ex2y.dat')

# On affiche les 5 premières valeurs pour vérifié 
print("x : \n",x[:5]) 
print("y : \n",y[:5]) 

x : 
 [[2.104e+03 3.000e+00]
 [1.600e+03 3.000e+00]
 [2.400e+03 3.000e+00]
 [1.416e+03 2.000e+00]
 [3.000e+03 4.000e+00]]
y : 
 [399900. 329900. 369000. 232000. 539900.]


2. Normalisation des données : 

In [22]:
import sklearn as sk

scaler = sk.preprocessing.StandardScaler()

dataX_norm = scaler.fit_transform(x,y)

print("Données normaliser :",dataX_norm[:5])

Données normaliser : [[ 0.13141542 -0.22609337]
 [-0.5096407  -0.22609337]
 [ 0.5079087  -0.22609337]
 [-0.74367706 -1.5543919 ]
 [ 1.27107075  1.10220517]]


3. 
Définir les fonctions en Python sous forme matricielle pour représenter la fonction d'hypothèse, le vecteur tel défini dans le cours :[...] , la fonction décrivanrt une itération et la fonction de coût J($\theta$) 

In [25]:

# On construit la matrice X augmentée et le vecteur Y 
X = np.c_[np.ones(dataX_norm.shape[0]), dataX_norm]
Y = y

print("\n Matrice X : \n",X[:5])
print("\n Vecteur Y : \n",Y[:5])

# Fonction hypothèse
def h(theta,X):
     return X @ theta


theta_test1 = np.array([1.0, 2.0, -0.5])  # [θ0, θ1, θ2]
test = h(theta_test1,X)
print("\nTest fonction d'hyothèse : \n",test)      


 Matrice X : 
 [[ 1.          0.13141542 -0.22609337]
 [ 1.         -0.5096407  -0.22609337]
 [ 1.          0.5079087  -0.22609337]
 [ 1.         -0.74367706 -1.5543919 ]
 [ 1.          1.27107075  1.10220517]]

 Vecteur Y : 
 [399900. 329900. 369000. 232000. 539900.]

Test fonction d'hyothèse : 
 [ 1.37587753  0.09376529  2.12886408  0.28984183  2.99103891  0.40900732
 -0.07413036 -0.34632483 -0.46588688 -0.1758853   0.29453301  1.11131468
  0.8314886   6.08673466 -0.75080071  1.21032746  0.04562998 -0.83220466
  1.99638437  3.06989899  0.51859216  1.49055012  0.10394078  0.35049822
  5.91923558 -1.17817146 -0.26746475  2.44939214  1.62008938  2.7317621
  1.36590032 -0.10426027  0.54892036  4.00369884 -0.03362667 -0.32088609
 -0.82457304  0.78295672  6.0818452   0.85927292  0.92072246  1.71675658
  1.88954169 -0.92378411 -1.14490282  0.07067214 -0.91615249]
